on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      createUser:
        description: 'search products'
        required: true
        default: '@create'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.9
        uses: actions/setup-java@v1
        with:
          java-version: 1.9
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master' }}
        name: Unit and Integration Tests by default fixture
        #        run: mvn clean verify -Dcucumber.filter.tags="@search-product-v1"
        run: mvn clean verify -Dcucumber.filter.tags=${{ github.event.inputs.createUser }}
      - if: ${{ github.event_name == 'workflow_dispatch' && github.event.pull_request.base.ref == 'master' }}
        name: Unit and Integration Tests by workflow_dispatch
        run: mvn clean verify -Dcucumber.filter.tags=${{ github.event.inputs.createUser }}

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: |
            ./target/site/serenity/

